source "https://rubygems.org"

# Usa la misma versión de Jekyll y plugins que GitHub Pages en producción.
# https://pages.github.com/versions/
gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end

# Windows y JRuby no incluyen zoneinfo por defecto.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", install_if: Gem.win_platform?

# Performance-booster para watching en Windows.
gem "http_parser.rb", "~> 0.6.0", install_if: Gem.win_platform?
